### ISSUE TITLE
Request: Random mix and master volume

### ISSUE THREAD

**Issue by superDuperCyberTechno** [abetusk/noixer#1]
2 requests:

1. A button to randomize the mix along with a number input so only x sounds are activated.
2. A master volume slider so you can mix the output with other sound sources from your system (music, videos).

**Comment by abetusk** [comment]
To clarify, the "randomize" button would take an extra input, potentially, that is a number, `N`, and would only randomize only `N` sounds together?

**Comment by abetusk** [comment]
ok, not sure if it's exactly what you wanted but this functionality now exists.

There is a 'global gain' near the top:

![glob_gain](https://user-images.githubusercontent.com/1406122/183264534-605f891c-e762-406a-aab9-b918f7406190.png)

Near the bottom, above the presets, there's a `rand N` button that can be used to pick a random number of sounds to play:

![rand_n](https://user-images.githubusercontent.com/1406122/183264548-81bdf03e-cd52-4802-9df0-ae87965029ca.png)

The random number can be adjusted with buttons to increment and decrement the number of random sounds (default start is 2). The volume isn't fiddled with, it just plays sounds and leaves the volume unchanged.

**Comment by superDuperCyberTechno** [comment]
Completely forgot about this. Thanks for updating it, works beautifully!
